FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/default.conf

# nginx config /etc/nginx/nginx.conf defines default site at
# /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html/
