apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-gcp
  name: hello-gcp
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-gcp
  type: LoadBalancer